Class {
	#name : #ERTemplateConferenceOptionsRegister,
	#superclass : #Object,
	#instVars : [
		'listGender',
		'listOfDays',
		'listOfFoodPreference',
		'tShirtSize'
	],
	#category : #'ESUGApp-Templates'
}

{ #category : #accessing }
ERTemplateConferenceOptionsRegister >> listGender [
	^ listGender
]

{ #category : #accessing }
ERTemplateConferenceOptionsRegister >> listGender: anObject [
	listGender := anObject
]

{ #category : #accessing }
ERTemplateConferenceOptionsRegister >> listOfDays [
	^ listOfDays
]

{ #category : #accessing }
ERTemplateConferenceOptionsRegister >> listOfDays: anObject [
	listOfDays := anObject
]

{ #category : #accessing }
ERTemplateConferenceOptionsRegister >> listOfFoodPreference [
	^ listOfFoodPreference
]

{ #category : #accessing }
ERTemplateConferenceOptionsRegister >> listOfFoodPreference: anObject [
	listOfFoodPreference := anObject
]

{ #category : #accessing }
ERTemplateConferenceOptionsRegister >> tShirtSize [
	^ tShirtSize
]

{ #category : #accessing }
ERTemplateConferenceOptionsRegister >> tShirtSize: anObject [
	tShirtSize := anObject
]
