Class {
	#name : #ERTemplateAffiliationInformationRegister,
	#superclass : #Object,
	#instVars : [
		'organizationName',
		'organizationAddress',
		'organizationCity',
		'organizationCountry',
		'organizationProvince',
		'organizationPostal',
		'membershipType'
	],
	#category : #'ESUGApp-Templates'
}

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> membershipType [
	^ membershipType
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> membershipType: anObject [
	membershipType := anObject
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> organizationAddress [
	^ organizationAddress
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> organizationAddress: anObject [
	organizationAddress := anObject
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> organizationCity [
	^ organizationCity
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> organizationCity: anObject [
	organizationCity := anObject
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> organizationCountry [
	^ organizationCountry
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> organizationCountry: anObject [
	organizationCountry := anObject
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> organizationName [
	^ organizationName
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> organizationName: anObject [
	organizationName := anObject
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> organizationPostal [
	^ organizationPostal
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> organizationPostal: anObject [
	organizationPostal := anObject
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> organizationProvince [
	^ organizationProvince
]

{ #category : #accessing }
ERTemplateAffiliationInformationRegister >> organizationProvince: anObject [
	organizationProvince := anObject
]
