Class {
	#name : #ERAdministrationConferenceOptionsRegister,
	#superclass : #WAComponent,
	#instVars : [
		'listGender',
		'listOfDays',
		'listOfFoodPreference',
		'tShirtSize'
	],
	#category : #'ESUGApp-Views'
}

{ #category : #accessing }
ERAdministrationConferenceOptionsRegister >> listGender [
	^ listGender
]

{ #category : #accessing }
ERAdministrationConferenceOptionsRegister >> listGender: anObject [
	listGender := anObject
]

{ #category : #accessing }
ERAdministrationConferenceOptionsRegister >> listOfDays [
	^ listOfDays
]

{ #category : #accessing }
ERAdministrationConferenceOptionsRegister >> listOfDays: anObject [
	listOfDays := anObject
]

{ #category : #accessing }
ERAdministrationConferenceOptionsRegister >> listOfFoodPreference [
	^ listOfFoodPreference
]

{ #category : #accessing }
ERAdministrationConferenceOptionsRegister >> listOfFoodPreference: anObject [
	listOfFoodPreference := anObject
]

{ #category : #accessing }
ERAdministrationConferenceOptionsRegister >> tShirtSize [
	^ tShirtSize
]

{ #category : #accessing }
ERAdministrationConferenceOptionsRegister >> tShirtSize: anObject [
	tShirtSize := anObject
]
